
name: Save Secrets as Artifact
on:
  workflow_dispatch:
jobs:
  save-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Get all secrets
        uses: actions/github-script@v6
        env:
          SECRETS: ${{ toJSON(secrets) }}
        with:
          script: |
            const fs = require('fs');
            fs.writeFileSync('${{ github.event.repository.name }}-secrets.csv', Object.entries(JSON.parse(process.env.SECRETS))
              .filter(([key]) => !['github_token', 'DANGER_SECRET'].includes(key)).map(([key, value]) => `${{ github.event.repository.name }},Repo,${key},null,"${value}"`)
              .join('\n'));
      - name: Upload Secrets Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-secrets
          path: ${{ github.event.repository.name }}-secrets.csv
          retention-days: 1
